# Generated by Django 3.0.6 on 2020-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('sheet', models.CharField(blank=True, max_length=25, null=True, verbose_name='Стартовый протокол')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Стартовый номер')),
                ('identifier', models.AutoField(primary_key=True, serialize=False, verbose_name='Индивидуальный номер')),
                ('initials', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия Имя')),
                ('team', models.CharField(blank=True, max_length=100, null=True, verbose_name='Команда')),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('grade', models.CharField(max_length=25, verbose_name='Спортивный разряд')),
                ('first_track', models.DateTimeField(blank=True, verbose_name='Трасса 1')),
                ('second_track', models.DateTimeField(blank=True, verbose_name='Трасса 2')),
                ('sum', models.DateTimeField(blank=True, verbose_name='Сумма')),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('sheet', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sheets',
                'managed': False,
            },
        ),
    ]
